
package carogame.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanCoPort", targetNamespace = "http://banCoService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanCoPort {


    /**
     * 
     * @param khoiTaoBanCoRequest
     * @return
     *     returns carogame.soapclient.KhoiTaoBanCoResponse
     */
    @WebMethod
    @WebResult(name = "khoiTaoBanCoResponse", targetNamespace = "http://carogameservice/ws", partName = "khoiTaoBanCoResponse")
    public KhoiTaoBanCoResponse khoiTaoBanCo(
        @WebParam(name = "khoiTaoBanCoRequest", targetNamespace = "http://carogameservice/ws", partName = "khoiTaoBanCoRequest")
        KhoiTaoBanCoRequest khoiTaoBanCoRequest);

    /**
     * 
     * @param kiemTraTinhHopLeRequest
     * @return
     *     returns carogame.soapclient.KiemTraTinhHopLeResponse
     */
    @WebMethod
    @WebResult(name = "kiemTraTinhHopLeResponse", targetNamespace = "http://carogameservice/ws", partName = "kiemTraTinhHopLeResponse")
    public KiemTraTinhHopLeResponse kiemTraTinhHopLe(
        @WebParam(name = "kiemTraTinhHopLeRequest", targetNamespace = "http://carogameservice/ws", partName = "kiemTraTinhHopLeRequest")
        KiemTraTinhHopLeRequest kiemTraTinhHopLeRequest);

    /**
     * 
     * @param kiemTraThangRequest
     * @return
     *     returns carogame.soapclient.KiemTraThangResponse
     */
    @WebMethod
    @WebResult(name = "kiemTraThangResponse", targetNamespace = "http://carogameservice/ws", partName = "kiemTraThangResponse")
    public KiemTraThangResponse kiemTraThang(
        @WebParam(name = "kiemTraThangRequest", targetNamespace = "http://carogameservice/ws", partName = "kiemTraThangRequest")
        KiemTraThangRequest kiemTraThangRequest);

}
