
package carogame.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BanCoPortService", targetNamespace = "http://banCoService", wsdlLocation = "http://localhost:8088/ws/banCo.wsdl")
public class BanCoPortService
    extends Service
{

    private final static URL BANCOPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANCOPORTSERVICE_EXCEPTION;
    private final static QName BANCOPORTSERVICE_QNAME = new QName("http://banCoService", "BanCoPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/ws/banCo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANCOPORTSERVICE_WSDL_LOCATION = url;
        BANCOPORTSERVICE_EXCEPTION = e;
    }

    public BanCoPortService() {
        super(__getWsdlLocation(), BANCOPORTSERVICE_QNAME);
    }

    public BanCoPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANCOPORTSERVICE_QNAME, features);
    }

    public BanCoPortService(URL wsdlLocation) {
        super(wsdlLocation, BANCOPORTSERVICE_QNAME);
    }

    public BanCoPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANCOPORTSERVICE_QNAME, features);
    }

    public BanCoPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanCoPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanCoPort
     */
    @WebEndpoint(name = "BanCoPortSoap11")
    public BanCoPort getBanCoPortSoap11() {
        return super.getPort(new QName("http://banCoService", "BanCoPortSoap11"), BanCoPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanCoPort
     */
    @WebEndpoint(name = "BanCoPortSoap11")
    public BanCoPort getBanCoPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://banCoService", "BanCoPortSoap11"), BanCoPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANCOPORTSERVICE_EXCEPTION!= null) {
            throw BANCOPORTSERVICE_EXCEPTION;
        }
        return BANCOPORTSERVICE_WSDL_LOCATION;
    }

}
